context:
  version: "0.12.0"

package:
  name: pomsky
  version: ${{ version }}

source:
  url: https://github.com/rulex-rs/pomsky/archive/v${{ version }}.tar.gz
  sha256: 98d2c3a45824c221554475817c198f7cf0a398ab47fd02083d8a15b18e458daa

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - pomsky --help

about:
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Regular expression language
  homepage: https://pomsky-lang.org
  repository: https://github.com/rulex-rs/pomsky

extra:
  recipe-maintainers:
    - danielnachun
